// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates(arg1) {
  return window['go']['main']['App']['CheckForUpdates'](arg1);
}

export function DeleteInstalledEnvironment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteInstalledEnvironment'](arg1, arg2, arg3, arg4);
}

export function DoUpdate(arg1) {
  return window['go']['main']['App']['DoUpdate'](arg1);
}

export function GetAvailablePort() {
  return window['go']['main']['App']['GetAvailablePort']();
}

export function GetInstalledEnvironments() {
  return window['go']['main']['App']['GetInstalledEnvironments']();
}

export function GetIp() {
  return window['go']['main']['App']['GetIp']();
}

export function GetKubernetesContexts() {
  return window['go']['main']['App']['GetKubernetesContexts']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function InstallEnvironment(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['InstallEnvironment'](arg1, arg2, arg3, arg4, arg5);
}

export function IsDockerInstalled() {
  return window['go']['main']['App']['IsDockerInstalled']();
}

export function IsDockerRunning() {
  return window['go']['main']['App']['IsDockerRunning']();
}

export function IsEnvironmentInstalled(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['IsEnvironmentInstalled'](arg1, arg2, arg3, arg4);
}

export function IsInternetConnected() {
  return window['go']['main']['App']['IsInternetConnected']();
}

export function IsKubernetesInstalled() {
  return window['go']['main']['App']['IsKubernetesInstalled']();
}

export function IsPortAvailable(arg1) {
  return window['go']['main']['App']['IsPortAvailable'](arg1);
}

export function OpenFolderDialog(arg1) {
  return window['go']['main']['App']['OpenFolderDialog'](arg1);
}

export function PopulateEnvironment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PopulateEnvironment'](arg1, arg2, arg3, arg4);
}

export function ReadEnvVariables(arg1) {
  return window['go']['main']['App']['ReadEnvVariables'](arg1);
}

export function SpecifyPlatformPath(arg1) {
  return window['go']['main']['App']['SpecifyPlatformPath'](arg1);
}
