name: Wails build

on: workflow_dispatch

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name: [App, App, App]
        platform: [linux/amd64, windows/amd64, darwin/universal]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.name }}
          build-platform: ${{ matrix.platform }}
          package: false
          go-version: '1.22.0'
