name: Wails build

on: workflow_dispatch

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'epos-data-portal-installer'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'epos-data-portal-installer'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'epos-data-portal-installer'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false    # Don't export as a release
          nsis: false       # Don't create an NSIS installer
          go-version: '1.22.0'

      # - name: Minisign Sign
      #   # Only sign on windows and linux
      #   if: matrix.build.platform != 'darwin/universal' 
      #   uses: thomasdesr/minisign-action@v1
      #   with:
      #     args: -Sm */bin/*
      #     minisign_key: ${{ secrets.minisign_key }}
      #     password: ${{ secrets.minisign_password }}

      # clone and build the go-minisign
      - name: Clone go-minisign
        run: |
          git clone https://aead.dev/minisign && cd minisign
          go build -o . aead.dev/minisign/cmd/minisign
          cd ..

      - name: Minisign Sign
        if: matrix.build.platform != 'darwin/universal' 
        env:
          INPUT_MINISIGN_KEY: ${{ secrets.minisign_key }}
          INPUT_PASSWORD: ${{ secrets.minisign_password }}
        run: |
          set -euo pipefail

          MINISIGN_KEY_PATH="${MINISIGN_KEY_PATH:-"$HOME/.minisign/minisign.key"}"
          [[ ! -z "${INPUT_MINISIGN_KEY:-}" ]] \
              && mkdir -p "$(dirname $MINISIGN_KEY_PATH)"\
              && echo "$INPUT_MINISIGN_KEY" > "${MINISIGN_KEY_PATH}"

          set +o pipefail
          (while true; do echo "${INPUT_PASSWORD:-}"; done) | (set -x; ./minisign/minisign -Sm */bin/*)
        