name: Wails build

on: 
  push:
    tags:
      - '*'

permissions:
  contents: write

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'epos-data-portal-installer-linux'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'epos-data-portal-installer-windows.exe'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'epos-data-portal-installer'  # The name here needs to be the same as the wails.json name
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false    # Don't export as a release
          nsis: false       # Don't create an NSIS installer
          go-version: '1.22.0'

      - name: Minisign Sign Linux
        if: matrix.build.platform == 'linux/amd64' 
        env:
          INPUT_RAW_PRIVATE_KEY: ${{ secrets.minisign_key }}
          INPUT_PASSWORD: ${{ secrets.minisign_password }}
          OUTPUT_SIGNATURE_NAME: 'linux-amd64-signature'
        run: |
          git clone https://github.com/Marco-Salvi/go-minisign-action.git
          cd go-minisign-action
          go build -o go-minisign-action
          ./go-minisign-action
          
      - name: Minisign Sign Windows
        if: matrix.build.platform == 'windows/amd64' 
        env:
          INPUT_RAW_PRIVATE_KEY: ${{ secrets.minisign_key }}
          INPUT_PASSWORD: ${{ secrets.minisign_password }}
          OUTPUT_SIGNATURE_NAME: 'windows-amd64-signature'
        run: |
          git clone https://github.com/Marco-Salvi/go-minisign-action.git
          cd go-minisign-action
          go build -o go-minisign-action.exe
          go-minisign-action.exe
          cd ..
        shell: cmd

      # Wails build on MacOS doesn't rename the binary, so we need to do it manually
      - name: MacOs binary rename
        if: matrix.build.platform == 'darwin/universal'
        run: |
          mv build/bin/epos-data-portal-installer.app build/bin/epos-data-portal-installer-macos.app

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            */bin/*
            go-minisign-action/*.minisig